# This is the workflow to lint the source code
name: Test

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: '🧫 Test Code'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v6

      - name: '🔧 Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: '⛓️ Install dependencies'
        run: npm ci

      - name: '🌍 Install Playwright browsers'
        run: npx playwright install --with-deps

      - name: '🧫 Run tests'
        run: npm run test --if-present

      - name: '📤 Upload test results'
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: test-results
          retention-days: 30
